### ISSUE TITLE
Please warn when code is Py2 only?

### ISSUE THREAD

**Issue by ghost** [Miserlou/Emo#1]
Just tried to install on 3.4 and was very 😞

**Comment by Miserlou** [comment]
Ugh, it's starting. All of my projects are Py2, I knew the day would come when Py3 would start knocking at my door.. I guess that time is now.

Does Python3 have a _from_past_ or something? I hate print(). Long live print!

**Comment by Miserlou** [comment]
Could this be a packaging thing? Could I define the interpreter in the setup.py file?

**Comment by ghost** [comment]
You can manually check the version tuple in `sys` and error out, but it 
already crashes on install. I meant a single line in the readme to warn 
people not to attempt with a modern interpreter.

And, yea; there is "from past" in the form of 2to3, but the changes to 
Py3 were breaking for a reason; they're non-trivial to get right 
automatically, so some warning still valuable.

In the setup.py file though, please remember to add metatags for the 
versions you do support. The conspicuous absence of anything since 2.7 
will make it clear that you don't support recent versions.

**Comment by Miserlou** [comment]
I'd rather just support Python3 I guess before I do any publicity around this project. If you feel like being a true G you can send a pull request and I'll merge it in, if not I'll update this with P3 support some time in the next few days. It's probably just the print statement, I don't know why else it wouldn't work with P3, it's such an incredibly simple program.

**Comment by Miserlou** [comment]
Okay, it was a 3 line fix, should work with python3 now.
